# Generated by Django 2.0.7 on 2018-09-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artcile',
            new_name='Article',
        ),
    ]
