# Generated by Django 2.0.7 on 2018-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180912_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=12),
        ),
    ]
