# Generated by Django 2.0.7 on 2018-09-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180904_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='another',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
