# Generated by Django 2.0.7 on 2018-09-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_another'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='another',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
    ]
