# Generated by Django 2.0.7 on 2018-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='image url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='description', max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default='summary'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='title', max_length=256),
        ),
    ]
