# Generated by Django 2.0.7 on 2018-09-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180904_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other',
            field=models.TextField(default='default'),
        ),
    ]
